apiVersion: apps/v1
kind: Deployment
metadata:
  name: c1
  namespace: mytg
spec:
  replicas: 5
  selector:
    matchLabels:
      env: prod
  template:
    metadata:  
      labels:
        env: prod
    spec:
      containers:
        - name: c1
          image: nginx
          ports:
            - containerPort: 80
