apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{.Chart.Name}}"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: santa
  template:
    metadata:
      labels:
        app: santa
    spec:
      containers:
        - name: "{{.Chart.Name}}"
          image: dockerhubdemosubha1234/newwebappsecretsanta:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8089
          resources:  # Optional resource constraints
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "1Gi"

---

apiVersion: v1
kind: Service
metadata:
  name: "{{.Chart.Name}}"
spec:
  selector:
    app: santa
  ports:
    - protocol: TCP
      port: 8089
      targetPort: 8089
  type: LoadBalancer